### PR TITLE
feat: Added reference scripts for binary classification

### PR DESCRIPTION
**Pull request by frgfm**
This PR adds a `reference` folder with training scripts for different tasks. More specifically, it provides two scripts for binary classification: one using only the core dependencies of `pyronear` and the other with `fastai`.

Users should note that the `fastai` one actually changes the model's architectures by complexifying the head. Performances are not comparable as is.

See #3

### CODE REVIEW

**Review by blenzi — CHANGES_REQUESTED** [review]
I could not make the script ```fastai_train.py``` work neither locally nor on colab.  Locally, first problem:
```
  File "references/classification/fastai_train.py", line 6, in <module>
    from fastai import vision
ModuleNotFoundError: No module named 'fastai'
```
fastai is not in the requirements, I can understand why. But at least a comment in the README or CONTRIBUTING would be useful.

Then:
```
python references/classification/fastai_train.py

Traceback (most recent call last):
  File "references/classification/fastai_train.py", line 77, in <module>
    main(args)
  File "references/classification/fastai_train.py", line 23, in main
    for sample in OpenFire(root=args.data_path, train=False, download=True).data:
  File "/Users/blenzi/cernbox/Workarea/PyroNear/pyronear/datasets/openfire.py", line 54, in __init__
    raise RuntimeError('Dataset not found.' +
RuntimeError: Dataset not found. You can use download=True to download it
```

Since download is already True I am not sure how to proceed. I tried to manually filling up the images folder with the ones that could not be downloaded and got the same error.

Would it be possible to add the scripts (or the functions called) to CI / unittests ?

**Comment by frgfm** [comment]
@blenzi fully agree with the comment on the readme for the requirements! I forgot to add a specific one for the `references` folder. I'll update this accordingly

Regarding the training script, I'm gonna run some tests but I don't see how to add it efficiently to CI. As you pointed out, the dataset download is already long, but since CI only has CPUs, the training (even for one epoch) would be way too long unfortunately...

**Comment by blenzi** [comment]
On the new version, running locally, no GPU:
```
  File "references/classification/fastai_train.py", line 28, in main
    df = pd.DataFrame.from_dict(dict(name=fnames, label=labels, is_valid=is_valid))
NameError: name 'pd' is not defined
```

If I add ```import pandas as pd```:

```
RuntimeError: DataLoader worker (pid 97793) is killed by signal: Unknown signal: 0.
```

Maybe we could add some tests (download, train, test) with a subset of the full dataset to make sure that the whole chain works ?

**Comment by frgfm** [comment]
@blenzi I just pushed a few commits that should your issues.

However, for CI integration, I guess we can test the scripts with `epochs=0` so we can at least check that the loading part is alright. But I see this as a separate topic _(me introducing a mistake in the script vs. testing this at each commit)_, would you mind opening an issue?

We'll flag this issue for the patch after the incoming release `0.1.0` (most likely for `0.1.1`).

**Review by blenzi — APPROVED** [review]

**Pull request merged**
