### PR TITLE
Pyronear engine

### PR DESCRIPTION
**Pull request by MateoLostanlen**
This class is the Pyronear Engine. This engine manage the whole Fire Detection process on raspberry pi by capturing and saving the image and by predicting if there is a fire or not based on this image

### CODE REVIEW

**Comment by frgfm** [comment]
Thanks @MateoLostanlen for the PR!
It's indeed a great feature, I'll look into the class shortly but I have a question:
- what is the .txt file in the PR? Is this a model checkpoint? If so, isn't it the wrong extension?
- assuming the file is actually more than 40Mb, I would suggest that we put it in the next release attachments, rather than in the source code. What do you think?

**Comment by MateoLostanlen** [comment]
Hi @frgfm, yes the txt file are the weights of the model. Ok I will remove it, if you think it's better this way

**Comment by frgfm** [comment]
> Hi @frgfm, yes the txt file are the weights of the model. Ok I will remove it, if you think it's better this way

For future reference, whether we put the checkpoint in the release attachments or somewhere else, it's better to use the `.pth` or `.pt` extension rather than `.txt` ;) (out of curiosity I tried to open the txt file with my IDE and found out it was a binary file)

**Comment by MateoLostanlen** [comment]
> > Hi @frgfm, yes the txt file are the weights of the model. Ok I will remove it, if you think it's better this way
> 
> For future reference, whether we put the checkpoint in the release attachments or somewhere else, it's better to use the `.pth` or `.pt` extension rather than `.txt` ;) (out of curiosity I tried to open the txt file with my IDE and found out it was a binary file)

ok thanks :)

**Comment by frgfm** [comment]
Just like in #81, I think this PR would be better on the embedded dedicated repo https://github.com/pyronear/PyronearEngine
If so, maybe we can close this PR and follow-up on the later?

**Comment by MateoLostanlen** [comment]
New repo for this topic : https://github.com/pyronear/PyronearEngine

I close the PR

**Pull request closed without merging**
