### PR TITLE
fix: Fixed CUDA collection for v11+

### PR DESCRIPTION
**Pull request by frgfm**
As mentioned @MateoLostanlen in #96, the CUDA version collection was failing with our current version of the script. As suspected, this is due to the regex used not being compatible with nvcc console output after version 11 cf. https://github.com/pytorch/pytorch/issues/51840

This PR fixes this using what was mentioned in the above issue, and now works both for CUDA>= 11 and CUDA < 11

### CODE REVIEW

**Comment by MateoLostanlen** [comment]
Hi @frgfm, thanks for the PR. Unfortunately, I still have the same output: 
```
Collecting environment information...
Pyrovision version: 0.2.0a0
PyTorch version: 1.7.1
Torchvision version: 0.8.2

OS: Microsoft Windows 10 Home

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not
```

**Comment by frgfm** [comment]
> Hi @frgfm, thanks for the PR. Unfortunately, I still have the same output:

Strange, it fixed it on my end! Could you post the output of the following commands please ?
```
nvcc --version
"C:\\Program Files\\NVIDIA Corporation\\NVSMI\\nvidia-smi"
"C:\\Program Files\\NVIDIA Corporation\\NVSMI\\nvidia-smi" -L
```
I may have to adapt the regex for windows support if this happens to be the issue.

**Comment by MateoLostanlen** [comment]
Ok I think the issue is on my side, nvcc was not working, now I have :

```
python scripts\collect_env.py
Collecting environment information...
Pyrovision version: 0.2.0a0
PyTorch version: 1.7.1
Torchvision version: 0.8.2

OS: Microsoft Windows 10 Home

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 11.2.67
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

```

and for your command :
```
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
```

Maybe one of the drivers is missing on my side

**Comment by frgfm** [comment]
@MateoLostanlen good news then! It looks like you still have issues with `nvidia-smi` but the rest looks good :ok_hand:
We can move forward with the PR review I think

**Review by MateoLostanlen — APPROVED** [review]

**Pull request merged**
