### PR TITLE
chore: Switched from CircleCI to GitHub workflow

### PR DESCRIPTION
**Pull request by frgfm**
This PR aims at changing CI from third-party CircleCI to Github workflow by:
- moving previous CI jobs to Github workflow
- adding a workflow to check documentation build status
- adding a workflow for documentation deployment

_Please note that CircleCI legacy checks are expected to fail since they are not run anymore_

### CODE REVIEW

**Comment by x0s** [comment]
Hi,
What problem are you trying to solve here ?
Best,

**Comment by frgfm** [comment]
> Hi,
> What problem are you trying to solve here ?
> Best,

CircleCI seemed to have issues over the last couple of days yielding failures in coverage uploads. Also, CircleCI being a third-party software while Github workflow allows PR contributors to look into corresponding checks directly in github (cf. https://github.com/frgfm/PyroNear/runs/684919682?check_suite_focus=true).

I did the switch myself on other open-source projects and haven't had any issues so far.

**Review by blenzi — APPROVED** [review]
Thanks @frgfm ! Indeed CircleCI is not working as well as previously, GitHub looks like a nice alternative.

**Comment by x0s** [comment]
@frgfm, @blenzi : It was not mentioned in the description, but does this PR imply that the project requirement moves from [python 3.6](https://github.com/frgfm/PyroNear/pull/68/files#diff-1d37e48f9ceff6d8030570cd36286a61L8) to [python 3.7](https://github.com/frgfm/PyroNear/pull/68/files#diff-05f841e90beeb81e84f0c31734ff4e28R16) ? o_O

**Comment by x0s** [comment]
Also, how can we check code style before pushing if `flake8` is [withdrawn](https://github.com/frgfm/PyroNear/pull/68/files#diff-2cc520ba52708aa2ab49c88c90e9e6bdL2) from `requirements` but [enforced in CI](https://github.com/frgfm/PyroNear/pull/68/files#diff-90829e76e906f1c73140c7ded7e1b268R79-R83) ?

**Comment by frgfm** [comment]
Not intentional for the Python version change, I'll update this! 
And regarding flake, I agree, let's put it back

**Pull request merged**
