### PR TITLE
Update project setup documentation to clarify virtualenvwrapper init (fix #70)

### LINKED ISSUE #70: Bug: "No module named virtualenvwrapper"
## 🐛 Bug

At Project Setup, when sourcing the bashrc to [create a virtual environment](https://github.com/frgfm/PyroNear/blob/master/CONTRIBUTING.md#1-create-a-virtual-environment), this error arouse

```
/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.
```

## To Reproduce

```
pip install virtualenvwrapper

# add at the end of your .bashrc
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh
```

## Expected behavior
Install properly virtual env, no error shown.

## Environment

-  OS: Ubuntu 20.04 LTS
 - Python version: 3.8.2

### PR DESCRIPTION
**Pull request by x0s**
This PR aims at updating the documentation to clarify environment setup and avoid python 2/3 conflict. Therefore it resolves #70

### CODE REVIEW

**Comment by x0s** [comment]
Hi @frgfm , any idea why the checks are failing and still using circle ci ?

**Comment by frgfm** [comment]
Regarding CircleCI, as some PRs were still pending when CI was changed, I left the webhook while they are not merged. For the checks, it's strange, I'll try something in another PR to address this while adapting your suggestions from #68!

**Comment by frgfm** [comment]
Same thing here, I think you just need to make any commit to trigger the workflows :)

**Comment by x0s** [comment]
@frgfm: Could you see any way the tests can fail with such changes in the code base so you are asking again to write fake commits ?

Those for migrated in a hurry from circleci to workflows may take their responsability in this regard. IMO, asking others to fiddle with their PRs is not a good way to maintain the repository.

**Comment by frgfm** [comment]
> @frgfm: Could you see any way the tests can fail with such changes in the code base so you are asking again to write fake commits ?
> 
> Those for migrated in a hurry from circleci to workflows may take their responsability in this regard. IMO, asking others to fiddle with their PRs is not a good way to maintain the repository.

Not at all, I'm happy reviewing this. You specifically asked me why the CI would fail, I'm suggesting a way to handle this. But with this change, I agree that untriggered tests are not a big issue.

**Review by frgfm — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
